services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    container_name: flask-app
    tty: true
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: sh -c "flask run --debug --host 0.0.0.0 --port 5000"
